### ISSUE TITLE
http://openwrt-dist.sourceforge.net/ 不可用了？

### ISSUE THREAD

**Issue by 70599** [aa65535/openwrt-dist-luci#10]
显示 "The sourceforge.net website is temporarily in static offline mode." 好几天了。
sourceforge的推特好像在说7/19日已恢复？可是错误信息也没变。
有打算做镜像/备份吗？

**Comment by aa65535** [comment]
是的，只是 http://sourceforge.net/projects/openwrt-dist 可以打开。

**Comment by NemoAlex** [comment]
有没有替代方案？现在都没地方下载了...

**Comment by 70599** [comment]
现在已经恢复了。
只是站点在墙外，我搞了个反代，不保证可用性。
http://7lab.eu.org/aa65535/

**Comment by aa65535** [comment]
可以在项目的 releases 中下载编译好的 ipk 文件。
之前sf已经恢复，不过依然不能上传文件，我稍后再看看。

2015年7月25日 14:23于 NemoAlex <notifications@github.com>写道：
有没有替代方案？现在都没地方下载了...

---
