### ISSUE TITLE
最新版本的chinadns配置菜单里面没有了压缩指针选择项？

### ISSUE THREAD

**Issue by kdrx** [aa65535/openwrt-dist-luci#11]
最新请问我已经升级到最新的 luci-app-chinadns 1.3.6-1 ，
菜单中只有 启用 启用双向过滤 没有启用关闭压缩指针菜单， 现在默认就启用压缩指针
而我是自建 server，不支持压缩指针的，这可如何是好，希望加上这个，可以自己选择开启关闭。

**Comment by aa65535** [comment]
No plan for this.
