### ISSUE TITLE
luci设置shadowsocks的访问控制只允许列表内似乎无效

### ISSUE THREAD

**Issue by hdstar2009** [aa65535/openwrt-dist-luci#13]
先说我对这个项的理解：访问控制选“仅允许列表内”，然后下面选择一个内网的ip地址，这样就设定只有这个ip地址才能通过ss访问。

如果我上面理解没错的话，那么这个功能可能有问题，我仅设置了pc的ip，但是我的手机一样可以通过ss访问y2b并能在国外网站监测出是ss服务器的ip地址。

**Comment by aa65535** [comment]
贴一下 `ipset save ss_spec_lan_ac` 打印的内容。

**Comment by hdstar2009** [comment]
[root@PandoraBox:/root]# ipset save ss_spec_lan_ac
create ss_spec_lan_ac hash:net family inet hashsize 1024 maxelem 65536
add ss_spec_lan_ac 192.168.1.214 nomatch


2015-09-02 21:01 GMT+08:00 Jian Chang <notifications@github.com>:

**Comment by aa65535** [comment]
从结果看并没有问题，确认手机是不是通过其他渠道翻墙了。

**Comment by hdstar2009** [comment]
没有，手机没其他设置。
我再观察下情况。

**Comment by SICKSOUL** [comment]
我也是这种情况
root@OpenWrt:~# ipset save ss_spec_lan_ac
create ss_spec_lan_ac hash:net family inet hashsize 1024 maxelem 65536
add ss_spec_lan_ac 192.168.1.101 nomatch
add ss_spec_lan_ac 192.168.1.102 nomatch

/etc/config/shadowsocks  配置文件内容是
        list lan_ac_ip '192.168.1.101'
	list lan_ac_ip '192.168.1.102'
	option lan_ac_mode '1'
求教

**Comment by aa65535** [comment]
fix in shadowsocks/openwrt-shadowsocks@b82f7c7e4b4172fa04459d951e048019f765dcd5

**Comment by hdstar2009** [comment]
如何更新这个？直接把那个shadowsocks.rule文件内容替换ss-rules的内容？
还是等新的2.4.2版的新release？

2015-11-12 18:40 GMT+08:00 Jian Chang <notifications@github.com>:

**Comment by aa65535** [comment]
@hdstar2009  直接修改ss-rules即可
