### ISSUE TITLE
shadowvpn的路由模式是否是表示选择了国内路由，国内路由表的地址就不通过vpn？

### ISSUE THREAD

**Issue by hdstar2009** [aa65535/openwrt-dist-luci#15]
shadowvpn的路由模式是表示选择了国内路由，国内路由表的地址就不通过vpn？还是说选择了国内路由那么国内路由表的都走vpn？

**Comment by aa65535** [comment]
参考 https://github.com/aa65535/openwrt-shadowvpn

 * **全局模式(0):** 启动后全部流量都经过 VPN  

 * **国内路由(1):** 路由文件中的 IP 将不经过 VPN, 如路由文件不存在则仍为**全局模式**  

 * **国外路由(2):** 只有路由文件中的 IP 经过 VPN, 如路由文件不存在则不使用 VPN
