### ISSUE TITLE
无法通过luci去enable ChinaDNS

### ISSUE THREAD

**Issue by bigZ-again** [aa65535/openwrt-dist-luci#17]
版本：luci-app-chinadns - 1.3.6-1

命令行下的/etc/init.d/chinadns [start|stop] 能够正常工作。

**Comment by aa65535** [comment]
`/etc/init.d/chinadns enable`

**Comment by bigZ-again** [comment]
我知道service 的start与enable的差别。我说的是luci 界面下的enable，按我理解选择enable后，save&apply 应该相当于执行service的start 和enable，反之，则执行stop和disable。但实际上，不论在Luci上怎样操作，都无法start 或stop service。

**Comment by bigZ-again** [comment]
这难道不是bug吗？luci的目的不是为了简化操作吗。
我对luci界面enable的理解来之luci-app-shadowsocks-spec - 1.3.6-1的界面表现！至少在luci可以方便的通过enable去控制shadowsocks的start/stop。
