### ISSUE TITLE
Is shadowsocks ignore list unsupported?

### ISSUE THREAD

**Issue by ExinCoda** [aa65535/openwrt-dist-luci#26]
just updated ss from
_shadowsocks-libev-spec_2.3.2_ + _luci-app-shadowsocks-spec_1.3.2_
to
_shadowsocks-libev-spec_2.4.5_ + _luci-app-shadowsocks-spec_1.3.8_

Switching between servers is easier now. But I cannot find ignore list in LuCI.
is it unsupported? will it be supported again? or i have to roll back :(

**Comment by cokebar** [comment]
ignore list is in WAN Access control

**Comment by ExinCoda** [comment]
thx @cokebar
