### ISSUE TITLE
wiki problem of openwrt-dist on sourceforge

### ISSUE THREAD

**Issue by cokebar** [aa65535/openwrt-dist-luci#28]
https://sourceforge.net/p/openwrt-dist/wiki/Plan5/

最后的配图，DNSMASQ的DNS转发地址填错地方了吧，图里填到“本地服务器”了，根据luci英文原文解释（Local domain specification. Names matching this domain are never forwarded and are resolved from DHCP or hosts files only），这里不应该填入转发地址，转发地址应填在下边“DNS转发”（DNS forwardings）里面：

**Comment by aa65535** [comment]
没有问题，「本地服务器」和「DNS转发」没有任何区别，在代码里都是已相同方式处理的。
https://github.com/aa65535/openwrt-dnsmasq/blob/master/files/dnsmasq.init#L147-L148
