### ISSUE TITLE
Submitting to Official OpenWRT Repository

### ISSUE THREAD

**Issue by clowwindy** [aa65535/openwrt-dist-luci#3]
There's already a [shadowsocks-client](https://github.com/openwrt/packages/pull/97) in official repo. Maybe we can submit shadowsocks-libev, ChinaDNS-C and ShadowVPN.

ref:
http://wiki.openwrt.org/doc/devel/packages#how_to_submit_patches_to_openwrt
https://dev.openwrt.org/wiki/SubmittingPatches

**Comment by aa65535** [comment]
I think we can try to do this, but I'm not sure whether it should be submitted with the shadowsocks-libev-spec and luci-apps, because they are still in the building.

**Comment by shifengjiang** [comment]
Hi internet freedom heros,

May I ask you a question? Is there any way to completely disable ss_rules in Shadowsocks Luci? Since ipset in dnsmasq already does everything for classifying traffic routes. Both 'Global Proxy' or 'Ignore List'  options in "Proxy Method" no longer make sense for this configuration.

**Comment by snowwolf007cn** [comment]
I think shadowsock-libev-spec is able to function properly most of the time, though still unsolved problems sometimes.
Committing to official repo will make it easy to install, since repo openwrt-dist.sourceforge.org is banned by GFW.

**Comment by ddqp** [comment]
wish to be submitted to official repo!!!!!!!!!!

**Comment by cokebar** [comment]
@shifengjiang You use dnsmasq-full + gfwlist to dnsmasq ipset rules + shadowsocks-libev right?
Then you should install shadowsocks-libev, not shadowsocks-libev-spec.
spec version is another method based on china route list.
