### ISSUE TITLE
The speed is not very fast compared to other version of shadowsocks

### ISSUE THREAD

**Issue by 1558204459** [aa65535/openwrt-dist-luci#30]
I compiled it for my wr740n route,i found the internet speed is very slow,the speed less than 100KB/s
when i used the shadowsocks-client package from openwrt official website,the speed is fast,it up to 1MB/s

**Comment by cokebar** [comment]
Check your DNS setting. You may connect to an remote server far away from your shadowsocks server due to an unsuitable DNS setting.
When you using shadowsocks-client, there's no similar problem cause you use ss-local instead of ss-redir.
