### ISSUE TITLE
A re-design of luci-app-shadowsocks access control UI

### ISSUE THREAD

**Issue by cokebar** [aa65535/openwrt-dist-luci#32]
@aa65535 你今天刚更新我就装了，很给力！不过使用luci-app时候目前这种排版让我对这个逻辑关系迷惑了很久，“常规”、“绕过”、“全局”这些描述容易让人疑惑。我思考了半天，想出了一个感觉更清晰的排版，仅供参考：https://cokebar.info/wp-content/uploads/2016/07/Image-3.png

**Comment by aa65535** [comment]
这样的话需要自定义 view 了, 等有时间了再弄吧, 说不定到时候大家也就习惯了 :-)

**Comment by aa65535** [comment]
fix in  b5855ee
