### ISSUE TITLE
这个项目和 https://github.com/shadowsocks/luci-app-shadowsocks 里的有什么区别？

### ISSUE THREAD

**Issue by pexcn** [aa65535/openwrt-dist-luci#35]

**Comment by cokebar** [comment]
aa65535编译的最新版本openwrt-shadowsocks只包含二进制文件 不再包含配置文件和init.d脚本 改由luci-app-shadowsocks带。 可以理解为换了个名字的新版本

**Comment by aa65535** [comment]
`luci-app-shadowsocks-spec` `+` `shadowsocks-libev-spec`  `==` `luci-app-shadowsocks` `+` `ss-{redir,tunnel}`
