### ISSUE TITLE
chinadns更新后因配置文件地址变更无法使用luci管理

### ISSUE THREAD

**Issue by nasbdh9** [aa65535/openwrt-dist-luci#41]
luci-app-chinadns | 1.6.1-1
ChinaDNS | 1.3.2-6

Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/chinadns is different from the conffile in the new package. The new conffile will be placed at /etc/config/chinadns-opkg.
 * resolve_conffiles: Existing conffile /etc/chinadns_chnroute.txt is different from the conffile in the new package. The new conffile will be placed at /etc/chinadns_chnroute.txt-opkg.

luci-app-chinadns | 1.6.1-1仍是认为配置文件路径是/etc/config/chinadns但新的配置文件路径为/etc/config/chinadns-opkg

**Comment by lixingcong** [comment]
这个不是本repo的锅，你在LEDE/Openwrt覆盖装任何一个高版本ipk文件都有这个提示。。。

```
The new conffile will be placed at xxxxxxxxxx-opkg.
```

**Comment by nasbdh9** [comment]
删掉重新装解决....
@lixingcong

**Comment by aa65535** [comment]
这是 OpenWrt 软件包管理的默认功能，如果配置文件有修改过是不会覆盖的，防止丢失自定义配置。

**Comment by cokebar** [comment]
新的配置文件并不是 /etc/config/chinadns-opkg，依然还是/etc/config/chinadns
这个警告是因为你新安装的ipk内带的配置文件在你系统中已经存在，安装程序不会覆盖你已有的配置文件，而是会将ipk包里的配置文件（相当于默认配置文件）重命名为xxx-opkg放置在同一个目录下。
如果你想改用默认配置，删除你原有的配置文件，并将xxx-opkg后面的-opkg去掉即可
如果你想保持你现在的配置，那就直接删除xxx-opkg
