### ISSUE TITLE
官网能不能申请个https证书啊？

### ISSUE THREAD

**Issue by zhanhb** [aa65535/openwrt-dist-luci#42]

**Comment by Biercenter** [comment]
@zhanhb openwrt-lede 的官方源也是http的，加了s貌似不能通过opkg安装

**Comment by zhanhb** [comment]
先安装好证书，然后 `ln -sfn /bin/wget /usr/bin/wget` 就可以用https了。
你这边可以http和https都开着，会用的用https，不会用的或者不想用的依然http

**Comment by zhanhb** [comment]
你有这个域名的完全权限的话申请证书很方便的，https://certbot.eff.org/

**Comment by cokebar** [comment]
这个repo哪有官网？ shadowsocks倒是有(shadowsocks.org)但是并不是aa65535管理的吧

**Comment by zhanhb** [comment]
https://sourceforge.net/p/forge/feature-requests/587/
好像只能http或者https，不能两个一起用

**Comment by zhanhb** [comment]
搭建了个http://openwrt-dist.sourceforge.net的镜像https://openwrt-dist.tk，过墙的时候走https
