### ISSUE TITLE
Menu cannot be hidden from main login page

### ISSUE THREAD

**Issue by fasthorse** [aa65535/openwrt-dist-luci#52]
On newly released 21.02 series OpenWRT, Menu cannot be hidden from main login page.
As mentioned following:
![image](https://user-images.githubusercontent.com/9995601/132310310-242bb4c4-0b73-44f6-9bc4-f97de2ef9140.png)
Please modify the code to satisfy the requirements of OpenWRT 21.02 series.

**Comment by aa65535** [comment]
Try to upgrade to 1.6.3.
