### ISSUE TITLE
能否在LUCI里提供一个开关，让用户自己决定是否自动运行 ss-rules ？

### ISSUE THREAD

**Issue by cqhtyi** [aa65535/openwrt-dist-luci#6]
spec的版本配合luci，在openwrt使用起来非常方便，但是我遇到了一个问题：
我希望ShadowSocks能在后台一直运行，但是我不希望使用SS的分流方案，或者我有更好的分流方案，再或者我是通过浏览器扩展设置具体的分流。
我现在是这么做的：
自己执行一次 ss-rules -f，但是重启防火墙之后，会重新创建新的防火墙规则，我必须再次执行ss-rules -f。
随后我改为，在luci里面的 “代理方式”，自定 all.list ，内容为 0.0.0.0/0 ，但是我不知道这么做会不会产生什么后果。
所以我希望作者能在luci里提供一个开关，让用户自己去决定是否自动运行 ss-rules。

**Comment by aa65535** [comment]
spec 版的主要功能就是由 ss-rules 提供的，所以不考虑添加这个开关。
过多的选项也会增加不熟悉的用户出错的概率。
如果需要「高级」的玩法，可以自己修改一下相应的代码即可。
