### ISSUE TITLE
安装后不显示

### ISSUE THREAD

**Issue by Joosun** [aa65535/openwrt-dist-luci#7]
安装 luci-app-chinadns_1.3.1-1_all.ipk、luci-app-shadowvpn_1.3.0-1_all.ipk 后不显示，没有定位的服务。

**Comment by Joosun** [comment]
尝试删除 /tmp/luci-indexcache 依旧无效。

**Comment by aa65535** [comment]
只安装 luci-app 是不行的，需要另外安装下面的两个 ipk
http://sourceforge.net/projects/openwrt-dist/files/chinadns/
http://sourceforge.net/projects/openwrt-dist/files/shadowvpn/

**Comment by Joosun** [comment]
这些都有装，装了这四个，软件包里面也有显示，
ChinaDNS 和 ShadowVPN 分别是这里下载的
http://sourceforge.net/projects/chinadns/files/dist/
https://github.com/clowwindy/ShadowVPN/releases

**Comment by aa65535** [comment]
只支持我提供的版本。

**Comment by Joosun** [comment]
这样哦，知道了。

**Comment by Joosun** [comment]
之前的版本是可以的，为什么更新后不行了呢？

**Comment by aa65535** [comment]
一直就不支持。

**Comment by LF905** [comment]
之前也遇到过这个问题，后在/etc/config中手动创建chinadns文件后就菜单就出现了。
