### ISSUE TITLE
Language files

### ISSUE THREAD

**Issue by eckertfo** [aa65535/openwrt-dist-luci#9]
Hi 

I am Working on an luci-app-freeradius2. And i want to add language files for englisch german and so on
Can you please tell me which tools does i need to make an  po files and when does they build during the build process.
I dont found any documentation who do i build language files doring the Build process in the makefile if the package is an out of tree package of the luci interface.

Kind regards

Flo

**Comment by aa65535** [comment]
Hi,

The .po file is a text file, you can use any text editor to create it.
In fact, Luci need an lmo file, you can use [po2lmo](https://github.com/aa65535/openwrt-dist-luci/tree/master/files/luci/tools/po2lmo) to generate it.
```shell
./po2lmo freeradius2.de.po freeradius2.de.lmo
```
All that remains is to specify a path in the [Makefile](https://github.com/aa65535/openwrt-dist-luci/blob/master/Makefile#L72).

Cheers,

Rin.

**Comment by eckertfo** [comment]
Thank you very mich for your help and reply
Am 07.05.2015 02:11 schrieb "Rin Satsuki" <notifications@github.com>:
